### PR TITLE
Add stylus plugins to the webpack:stylus package

### PR DESCRIPTION
**Pull request by jptissot**

### CODE REVIEW

**Comment by eXon** [comment]
Hey thank you for your PR.

I'm not sure the way you built this is flexible enough. You have hard-coded some plugins but their is no way to choose what plugins you would like to use with stylus.

Go look at the postcss plugin. I think it should work the same way.

**Comment by jptissot** [comment]
Thanks for looking it up. I will modify this PR to be more flexible. I'm guessing a user will have to manually add the dependencies to the package.json file and then reference the plugins via webpack.json ?

**Comment by eXon** [comment]
Exactly. I've changed the stylus package today so you might want to merge with master first. There is some major changes.

**Comment by zaklampert** [comment]
@jptissot thanks for doing this.

**Comment by jptissot** [comment]
@zaklampert  thanks for writing it in the first place. I updated the plugin, version and readme. Let me know what you think.

**Comment by eXon** [comment]
It looks awesome to me. I'll try it a bit to see how it behave.

**Comment by Svenskunganka** [comment]
@eXon @jptissot awesome work guys, really looking forward to this! Do you have any est. when this PR can be pulled?

Cheers!

**Comment by eXon** [comment]
@Svenskunganka should be done in the upcoming days.

**Pull request merged**
