### PR TITLE
Add support for "resolve.alias" and "resolve.modules"

### PR DESCRIPTION
**Pull request by rvetere**
i need this for my current project as it makes much more nicer import's possible.

With that i can define a "modules" array or an "alias" object like this in webpack.json:
```
"resolve": {
  "alias": {
     "App": "src/client/screens/App"
  },
  "modules": [
     "app",
     "components"
     "screens",
     "shared",
     "node_modules"
  ]
}
```

And so instead of writing:

`import Field from '../../../components/Field'`
`import Home from 'src/client/screens/App/screens/Home'`

We can shorten it to:

`import Field from 'Field'`
`import Home from 'App/screens/Home'`

### CODE REVIEW

**Comment by jschlieber** [comment]
Please merge! I would also need this to prevent having multiple copies of React in the bundle with:
```javascript
	
{
  ...
  resolve: {
    alias: {
      react: path.resolve('./node_modules/react'),
    },
  },
}
```

**Comment by SachaG** [comment]
@jschlieber sorry if it's a noob question, but in your example in which file would you put that code?

**Comment by rvetere** [comment]
@SachaG there are no noob-questions, only noob-answers ;)

Right, all those info's you ask go into the "webpack.json" file of a project which uses "meteor-webpack". Now the problem is that the currently released version of "meteor-webpack" is ignoring everything you define for "resolve.alias" or "resolve.modules".

My change i've done here and want to merge into the project would exactly solve this - he starts to look for those configurations and puts them into the webpack-conf he actually builds in the background.

@eXon just give me repo-admin at some point and i start to merge my PR's on my own which are so much asked 😄

**Comment by SachaG** [comment]
Oh ok, I was just confused because `react: path.resolve('./node_modules/react')` is not valid JSON. But I guess that's a webpack thing?

And yes I know about the`/packages` folder ;) But personally I use the PACKAGE_DIRS technique for this: 

http://stackoverflow.com/questions/18290516/how-do-i-link-the-environment-variable-package-dirs-to-my-local-private-package

**Comment by SachaG** [comment]
Oh ok, I got confused between `webpack.json` and `webpack.config.js`. @rvetere's code goes in the first one, and @jschlieber's in the second one. I'm guessing they both do the same thing though?

**Comment by SachaG** [comment]
(BTW this PR throws an error if `settings.resolve` isn't present)

**Comment by rvetere** [comment]
Oh noes sorry - now i am the stupid noob :P I didn't spend enough time to closely look at your question.

Your totally right! Of course "path.resolve" is not valid in a json file.

The code in  the end need to do a thing with "path.resolve" - but this code is part of the "WebpackCompiler.js" here in this package.

It works like this -> "webpack.json" is taken from the project root by this package here. It reads then all the infos out of this json file and parse all the things together in the "WebpackCompiler.js".

So in the webpack.json we're just giving him plain objects - like i'm showing in the intial discussion. And then WebpackCompiler.js takes those and processes them further if needed.

Thanks a lot for the hint - i'm just going to fix this last bug then ;)

**Comment by SachaG** [comment]
But is this PR really needed since you can already do all that in `webpack.config.js`, which seems to be loaded here?

https://github.com/thereactivestack/meteor-webpack/blob/master/packages/webpack/plugin/webpack-plugin.js#L10

**Comment by rvetere** [comment]
Yes and no :) Of course you could just give him a "webpack.config.js" File - but then you have to do all of the webpack stuff on your own!

This is not the initial idea of this package - it is thought is kind of a fallback if you are really unlucky to reach what you want. But i rather wanted to improve the basic functionality of the webpack package here so this is possible trough the "webpack.json" config which is LOT easier to handle than the original "webpack.config.js".

Especially if you take it together with all the other packages here in place - you can just drop them in your .meteor/packages too and it will take place in the dynamic generated "webpack.config.js" which he builds internally.

The work you get done by all this packages is insane - eXon did really an awesome job by offering all those simple packages.

**Comment by SachaG** [comment]
Oh ok, that makes total sense now :)

**Comment by veeramarni** [comment]
I took those changes and tested my code but it fails with below error

```
webpack_reload.js?hash=776c80c…:62 GET http://localhost:3500/assets/web.js 
```

webpack.json

```
{
  "root": "src",
  "devServer": {
    "host": "localhost"
  },
  "resolve": {
    "alias": {
      "react": "node_modules/react"
    }
  }
}
```

**Comment by rvetere** [comment]
Mmhm well but as far as i can think, an "Invariant Violation" has absolutely nothing to do with webpack and the resolve part at all. This is solely react causing this.

On the other side - an alias for "react": "node_modules/react" is completely useless. Because node_modules is one of those folders which is anyways defined as "module" folder for webpack - he's going to search in this folder anyways for dependent packages.

You can already write today:

`import React from 'react';`

Without having this alias and it already works perfect.

**Comment by SachaG** [comment]
Wouldn't it be better to do `webpackConfig.resolve.alias = _path.resolve(settings.resolve.alias);`?

Otherwise it seems like you have to specify an absolute path?

**Comment by rvetere** [comment]
@SachaG wow yes, didn't thought about that... i think i try to pick this approach and improve the codebase even more, thanks ;)

**Comment by eXon** [comment]
Awesome. Thanks for that PR!

**Comment by veeramarni** [comment]
@eXon  Can you take @SachaG  changes as well?

```
  // iterate through alias properties and resolve paths
      _.keys(settings.resolve.alias).forEach(key => {
        const absolutePath = _path.resolve(settings.resolve.alias[key]);
        settings.resolve.alias[key] = absolutePath;
      });

      webpackConfig.resolve.alias = settings.resolve.alias;

```

**Pull request merged**
