### PR TITLE
Remove "const" from sass webpack.config.js

### PR DESCRIPTION
**Pull request by MKRazz**

### CODE REVIEW

**Comment by rvetere** [comment]
i don't understand... just check if "es5-shim" is on your packages file and const should just work. Regarding the devolpement of JS itself, i would propose to go further down the road instead of crawling back to the beginning...

For me theres only one way to proceed - forward... and not backwards! Get used to "const" and "let", forget var already today and just work with babel and your all fine in all your projects ;)

**Comment by MKRazz** [comment]
Babel doesn't apply to webpack.config.js does it?

**Comment by rvetere** [comment]
@MKRazz yes i think your right... this was a little philosophical in my answer to take babel within.

i'm not sure which one of the packages is giving the possibility to use es6 features in package code - but i can also remember that the whole meteor stack is basically supporting es6 out-of-the-box... at least what i can remember from the docs.

i never ran in a problem using "const" or other es6 features in package code when i was tweaking around anything, so i just was wondering why such a PR would be needed then

**Comment by MKRazz** [comment]
I should have included a note about why. `const` appears to be supported in newer browsers but when I ran it on IE < 11 it throws an error.

I love `const` and `let`, I felt very dirty writing `var` for the PR.

**Comment by rvetere** [comment]
aah ok :) but this is extremely strange if you see the error in a browser! i was thinking you see the error during startup of your meteor process...

but then the much more important question is - why the heck does your IE11 even get this code provided? it is the package "sass" of "meteor-webpack".. this is a package that actually only runs during the build-phase of meteor - it's only used and executed on the server, even as a pre-process.

So - in any case i could think of, this code can never land in the browser oO

Of course the browser can't handle const, but this is not only IE but ALL of the browser as nobody is currently suppoting ES6 out-of-the-box. This is why there are tools like babel to "transpile" your ES6 code back to ES5 just to deliver the stuff to any browser.. But well it's also new to me that new browser (bigger than IE 11) are supporting const as you say... i doubt that oO

So it would be much more interesting now how in the hell you are able to get into this error - and i'm kinda sure this PR isn't needed at all in the end ;)

**Comment by djhi** [comment]
You can use es6 with webpack config by renaming it 'webpack.config.babel.js'

**Comment by eXon** [comment]
Thanks for the fix!

**Pull request merged**
